
# Fichier de configuration principal du projet DBT.
# Ce fichier définit le nom du projet, la version, et le comportement des modèles.

name: canal_data_platform                     
version: '1.0.0'                              
config-version: 2                             

 # Nom du profil de connexion à Redshift
profile: canal_data_platform                 

# Ici nous allons définir les chemins vers chaque type de fichier. Ainsi dbt saura où les trouver.

model-paths: ["models"]                       
analysis-paths: ["analyses"]                  
test-paths: ["tests"]                         
seed-paths: ["seeds"]                         
macro-paths: ["macros"]                       
snapshot-paths: ["snapshots"]                 

# Dossiers supprimés par la commande dbt clean
clean-targets:                             
  - "target"                                  
  - "dbt_packages"                        

models:
  canal_data_platform:                        

    staging:                                 
      +materialized: view                
      +schema: staging                     

    mart:                                  
      +materialized: table                   
      +schema: mart                        
